project_name: ramdisk
before:
  hooks:
    - go mod download
builds:
- main: ./cmd/ramdisk/ramdisk.go
  env:
    - CGO_ENABLED=0
  goos:
    - linux
    - darwin
  goarch:
    - amd64
    - arm64
archives:
- replacements:
    darwin: macOS
    amd64: x64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
brews:
  -
    tap:
      owner: mroth
      name: homebrew-tap
    description: Convenience wrapper for creating RAM disks.
    homepage: https://github.com/mroth/ramdisk
    skip_upload: false
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - '^trivial:'
    - '^release:'
