language: go
go:
  - "1.17.x"

matrix:
  include:
    # utilize xcode builds to test different macOS versions,
    # see: https://docs.travis-ci.com/user/reference/osx/#macos-version
    - name: macOS 11.6
      osx_image: xcode13.1 # => macOS 11.6
      os: osx
    - name: macOS 10.15
      osx_image: xcode12.2 # => macOS 10.15.7
      os: osx
    - name: macOS 10.14
      osx_image: xcode11.3 # => macOS 10.14.6
      os: osx
    - name: macOS 10.13
      osx_image: xcode10.1 # => macOS 10.13
      os: osx
    - name: macOS 10.12
      osx_image: xcode9.2 # => macOS 10.12
      os: osx
    # linux requires sudo to run our integration tests
    - name: Linux
      os: linux
      sudo: required
      env: SUDO_REQUIRED=true

script:
  - |
    if [ "${SUDO_REQUIRED}" == "true" ]; then
      sudo env "PATH=$PATH" go test -v
    else
      go test -v
    fi
