name: test
on: push

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - "macos-12"
          - "macos-11"
          - "macos-10.15"
          - "ubuntu-22.04"
          - "ubuntu-20.04"
          - "ubuntu-18.04"
        go: ["1.18"]
    name: ${{ matrix.os }} test
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
      - name: Run test
        run:  |
          if [ "$(uname)" == "Linux" ]; then
            sudo go test -v
          else
            go test -v
          fi

